django_movie/django_movie/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("", include("movies.urls")),
]


if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django_movie/movies/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.MoviesView.as_view()),
    path("filter/", views.FilterMoviesView.as_view(), name="filter"),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    #path("json-filter/", views.JsonFilterMoviesView.as_view(), name="json_filter"),    
    path("<slug:slug>/", views.MovieDetailView.as_view(), name="movie_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("actor/<str:slug>/", views.ActorView.as_view(), name="actor_detail"),
    
    
]

django_movie/movies/models.py
from django.db import models
from datetime import date
from django.urls import reverse



class Category(models.Model):
    """Категории"""
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категория" 


class Actor(models.Model):
    """Актеры и режиссеры"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def get_absolute_url(self):
        return reverse("actor_detail", kwargs={"slug": self.name})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры" 



class Genre(models.Model):
    """ Жанры"""
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique = True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанр" 


class Movie(models.Model):
    """Фильмы"""
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default= 2019)
    country = models.CharField("Страна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="Режиссер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="актеры", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premiere = models.DateField("Премьера в мире", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", default = 0, help_text="указывать сумму в долларах")
    fees_in_usa = models.PositiveIntegerField("Сборы в США", default=0, help_text="указать сумму в долларах")
    fees_in_world = models.PositiveIntegerField("Сборы в мире", default=0, help_text="указывать ссуму в долларах")
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null= True)
    url = models.SlugField(max_length=160, unique = True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title 
    
    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})
    
    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)
    class Meta: 
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    class Meta: 
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'
    
    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм")

    def __str__(self):
        return f"{self.star} - {self.movie}"
    
    class Meta:
        verbose_name =  "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank = True, null = True
    )
    movie = models.ForeignKey(Movie, verbose_name="фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"
    
    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

    

    

django_movie/movies/forms.py
from django import forms
from .models import Reviews, Rating, RatingStar


class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    class Meta: 
        model = Reviews
        fields =  ("name", "email", "text")


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect, empty_label=None
    )

    class Meta: 
        model = Rating
        fields = ("star",)

django_movie/movies/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from django.http import JsonResponse, HttpResponse
from django.db.models import Q

from .models import Actor, Movie, Category, Genre, Rating
from .forms import ReviewForm, RatingForm


class GenreYear:
    """Жанры и года выхода фильмов"""
    def get_genres(self):
        return Genre.objects.all()
    
    def get_years(self):
        return Movie.objects.filter(draft=False).values("year")

class MoviesView(GenreYear, ListView):
    """Список фильмов"""

    model =  Movie
    queryset = Movie.objects.filter(draft=False)
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args , **kwargs)
        context["categories"] = Category.objects.all()
        return context




class MovieDetailView(GenreYear, DetailView):
    """Полное описание фильма"""
    model = Movie
    slug_field = "url"

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        return context

class AddReview(View):
    """Отзывы"""
    def post(self,request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        print(form.is_valid())
        if form.is_valid():
            form= form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie= movie
            form.save()
        return redirect(movie.get_absolute_url())
    

class AddStarRating(View):
    """Добавление рейтинга фильму"""

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

class ActorView(GenreYear, DetailView):
    """Вывод информаации об актере"""
    model = Actor
    template_name = 'movies/actor.html'
    slug_field= "name"

class FilterMoviesView(GenreYear, ListView):
    """Фильтр фильмов"""
    def get_queryset(self):
        queryset = Movie.objects.filter(Q(year__in=self.request.GET.getlist("year"))|
                                        Q(genres__in=self.request.GET.getlist("genre")))
        return queryset
    

class JsonFilterMoviesView(ListView):
    """Фильтр фильмов в Json"""
    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year"))|
            Q(genres__in=self.request.GET.getlist("genre"))
            ).distinct().values("title", "tagline", "url", "poster")
        return queryset
    
    def get(self, request, *args, **kwargs):
        queryset = list(self.get_queryset())
        return JsonResponse({"movies": queryset}, safe=False)

django_movie/templates/movies/actor.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %} {{actor.name}} {% endblock title%}
{% block container %}
<div class="container py-md-3">
    {% endblock container %}

    {% block sidebar %}
    <div class="side-bar col-lg-4">
        {% endblock sidebar %}
        {% block movie %}
        <div class="left-ads-display col-lg-8">
            <div class="row">
                <div class="desc1-left col-md-6">
                    <img src="{{actor.image.url}}" class="img-fluid" alt="">
                </div>
                <div class="desc1-right col-md-6 pl-lg-4">
                    <h3 class="editContent">
                        {{movie.title}}</h3>
                    <h5 class="editContent"></h5>
                    <ul>
                        <li><span><b>Возраст:</b> {{actor.age}} лет</span></li>
                        <li>
                            <span><b>Режиссер:</b>
                                {% for movie in actor.film_director.all %}
                                {{movie.title}}
                                {% endfor %}</span>
                        </li>
                        <li><span><b>Актер:</b>
                                {% for movie in actor.film_actor.all %}
                                {{movie.title}}
                                {% endfor %}
                            </span></li>
                </div>
            </div>
            <div class="row sub-para-w3layouts mt-5">
                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                    О {{actor.name}}</h3>
                <p class="editContent">
                    {{actor.description|safe}}
                </p>
            </div>
        </div>
        {% endblock movie %}

django_movie/templates/movies/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title%}
{% block content %}

<section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
    {% block container %}
    <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
            <div class="side-bar col-lg-3">
                {% endblock sidebar %}
                {% include 'include/sidebar.html'%}
            </div>
            {% block movie %}
            {% endblock movie %}

        </div>
    </div>
</section>

{% endblock content%}

django_movie/templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %} {{movie.title}} {% endblock title%}
{% block container %}
<div class="container py-md-3">
    {% endblock container %}

    {% block sidebar %}
    <div class="side-bar col-lg-4">
        {% endblock sidebar %}
        {% block movie %}
        <div class="left-ads-display col-lg-8">
            <div class="row">
                <div class="desc1-left col-md-6">
                    <img src="{{movie.poster.url}}" class="img-fluid" alt="">
                </div>
                <div class="desc1-right col-md-6 pl-lg-4">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                        {{movie.title}}</h3>
                    <h5 class="editContent">Terminator: Dark Fate</h5>
                    <ul>
                        <li style="list-style: none"><span><b>Год:</b> {{movie.year}}</span></li>
                        <li style="list-style: none"><span><b>Страна:</b> {{movie.country}}</span>
                        </li>
                        <li style="list-style: none"><span><b>Слоган:</b> {{movie.tagline}}</span>
                        </li>
                        <li style="list-style: none">
                            <span><b>Режиссер:</b>
                                {% for director in movie.directors.all %}
                                <a href="{{director.get_absolute_url }}">{{director.name}}</a>

                                {% endfor %}</span>
                        </li>
                        <li style="list-style: none"><span><b>Актеры:</b>
                                {% for actor in movie.actors.all %}
                                <a href="{{actor.get_absolute_url }}">{{actor.name}}</a>

                                {% endfor %}
                            </span></li>
                        <li style="list-style: none"><span><b>Жанр:</b>
                                {% for director in movie.genres.all %}
                                {{genre.name}}
                                {% endfor %}
                            </span>
                        </li>
                        <li style="list-style: none"><span><b>Премьера в
                                    мире:</b>{{movie.world_premiere}}</span>
                        </li>
                        <li style="list-style: none">
                            <span><b>Бюджет:</b> {{movie.budget}}</span>
                        </li>
                        <li style="list-style: none">
                            <span><b>Сборы в США:</b> ${{movie.fees_in_usa}}</span>
                        </li>
                        <li style="list-style: none"><span><b>Сборы в мире:</b>
                                ${{movie.fees_in_world}}</span>
                        </li>
                        <li style="list-style: none">
                            <form action="{% url 'add_rating' %}" method="post" name="rating">
                                <b>Рейтинг:</b>
                                {% csrf_token %}
                                <input type="hidden" value="{{ movie.id }}" name="movie">
                                <span class="rating">
                                    {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star" value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                    {% endfor %}
                                </span>
                                <span class="editContent">4.0</span>
                            </form>
                        </li>
                        <div class="share-desc">
                            <div class="share">
                                <h4 class="editContent">
                                    Share:</h4>
                                <ul class="w3layouts_social_list list-unstyled">
                                    <li>
                                        <a href="#" class="w3pvt_facebook editContent"
                                            style="outline: none; cursor: inherit;">
                                            <span class="fa fa-facebook-f"
                                                style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="w3pvt_twitter editContent"
                                            style="outline: none; cursor: inherit;">
                                            <span class="fa fa-twitter" style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="w3pvt_dribble editContent"
                                            style="outline: none; cursor: inherit;">
                                            <span class="fa fa-dribbble" style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                </div>
            </div>
            <div class="row sub-para-w3layouts mt-5">

                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                    О фильме {{movie.title}}</h3>
                <p>
                    {% for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots " alt="{{ image.description }}">
                    {% endfor %}
                </p>
                <p class="editContent">
                    {{movie.description|safe}}
                </p>
                <p class="mt-3 italic-blue editContent" style="outline: none; cursor: inherit;">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"
                        frameborder="0"
                        allow="accelerometer; autoplay;
                                                                           encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen>

                    </iframe>
                </p>
            </div>
            <hr>
            <div class="row">
                <div class="single-form-left">
                    <!-- contact form grid -->
                    <div class="contact-single">
                        <h3 class="editContent" style="outline: none; cursor: inherit;">
                            <span class="sub-tittle editContent"> {{movie.reviews_set.count}}</span>Оставить
                            отзыв
                        </h3>
                        <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                            <div class="form-group editContent" style="outline: none; cursor: inherit;">

                                {% csrf_token %}
                                <input type="hidden" name="parent" id="contactparent" value="">
                                <label for="contactcomment" class="editContent">Ваш
                                    комментарий
                                    *</label>
                                <textarea class="form-control border" rows="5" name="text" id="contactcomment"
                                    required=""></textarea>
                            </div>
                            <div class="d-sm-flex">
                                <div class="col-sm-6 form-group p-0 editContent">
                                    <label for="contactusername" class="editContent">Имя
                                        *</label>
                                    <input type="text" class="form-control border" name="name" id="contactusername"
                                        required="">
                                </div>
                                <div class="col-sm-6 form-group ml-sm-3 editContent"
                                    style="outline: none; cursor: inherit;">
                                    <label for="contactemail" class="editContent">
                                        Email
                                        *</label>
                                    <input type="email" class="form-control border" name="email" id="contactemail"
                                        required="">
                                </div>
                            </div>
                            <button type="submit" class="mt-3 btn btn-success btn-block py-3"
                                style="outline: none; cursor: inherit;">Отправить
                            </button>
                        </form>
                    </div>
                    <!--  //contact form grid ends here -->
                </div>
                {% for review in movie.get_review %}
                <div class="media py-5">
                    <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                    <div class="media-body mt-4">
                        <h5 class="mt-0 editContent">
                            {{review.name}}
                        </h5>
                        <p class="mt-2 editContent">
                            {{review.text}}
                        </p>
                        <a href="#formReview" onclick="addReview('{{review.name}}', '{{review.id}}')">Ответить</a>
                        {% for rew in review.reviews_set.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="{% static 'images/te1.jpg' %}" class="img-fluid " alt="image"
                                    style="outline: none; cursor: inherit;">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent">{{rew.name}}</h5>
                                <p class="mt-2 editContent">{{rew.text}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <script>
            function addReview(name, id) {
                document.getElementById("contactparent").value = id
                document.getElementById("contactcomment").innerText = `${name}, `
            }
        </script>
        {% endblock movie %}

django_movie/templates/movies/movie_list.html
{% extends 'movies/base.html' %}

{% block header %} bg1 {% endblock header %}
<div class="left-ads-display col-lg-9">
    <div class="row">

        {% block movie%}
        {% for movie in movie_list %}
        <div class="col-md-4 product-men">
            <div class="product-shoe-info editContent text-center mt-lg-4">
                <div class="men-thumb-item">
                    <img src="{{movie.poster.url}}" class="img-fluid" alt="">
                </div>
                <div class="item-info-product">
                    <h4 class="">
                        <a href="{{movie.get_absolute_url}}" class="editContent">
                            {{movie.title}}
                        </a>
                    </h4>

                    <div class="product_price">
                        <div class="grid-price">
                            <span class="money editContent">{{movie.tagline}}</span>
                        </div>
                    </div>
                    <ul class="stars">
                        <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star-o" aria-hidden="true"></span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock movie %}